http:
  port: "8092"
  
anypoint:
  api:
    id: "1"
    validation: "3"
  
  app:
    clientId: "xxxxx"
    clientSecret: "yyyyy"

racedata:
  host: localhost
  port: "8093"
  protocol: HTTP
  path: /api

  
scorekeeper:
  host: localhost
  port: "8094"
  protocol: HTTP
  path: /api

practice:
  expiry: "3600" # seconds
  
  
challenge:
  aiagent:
    speakname:
      minScore: "4"
      timeout: "0.002"